name = "Ashen Anvil Empire"
author = "C Hartin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea1ff1606ead4a3a9068c487cf241a4955f3c6ae5c61cc4d752c848af53eb6c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"
