name = "Ashen Anvil Empire"
author = "C Hartin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee3593e64bdc80e29be65ef17fcdfb0b14fde4da2342b39ca1ceedfdbd3cd7bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"
