name = "Ashen Anvil Empire"
author = "C Hartin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa7e2d47fcc14f77a16c08bf24d97ce9b674501e1c0995c78d0d6bfa173d00e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"
